{
 "title": "AWS Quota Checker",
 "tags": [ "AWS" ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "MinQuotaThreashold",
    "label": "Only show quotas with % and higher",
    "query": "30, 40, 50"
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(awsquota_check_count,region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "AWS Quota Checker limits utilization ($MinQuotaThreashold% and higher)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Account level AWS Quota Checker ($MinQuotaThreashold% and higher)",
   "type": "bargauge",
   "description": "Dynamic list of all account level service quotas fetched by [aws-quota-checker](https://github.com/gravitational/aws-quota-checker)\n- https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html\n",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((max by(quota, account, service_code) ({__name__=~\"awsquota_.*_count\", exported_instance=\"\", scope=\"ACCOUNT\"}) / max by(quota, account, service_code) ({__name__=~\"awsquota_.*_count_limit\", exported_instance=\"\", scope=\"ACCOUNT\"})) >= $MinQuotaThreashold/100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[${region}] Regional AWS Quota Checker limits ($MinQuotaThreashold% and higher)",
   "type": "bargauge",
   "description": "Dynamic list of all regional service quotas fetched by [aws-quota-checker](https://github.com/gravitational/aws-quota-checker)\n- nhttps://docs.aws.amazon.com/general/latest/gr/aws-service-information.html\n",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc((max by(quota, region, service_code) ({__name__=~\"awsquota_.*_count\", region=~\"$region\", exported_instance=\"\", scope=\"REGION\"}) / max by(quota, region, service_code) ({__name__=~\"awsquota_.*_count_limit\", region=~\"$region\", exported_instance=\"\", scope=\"REGION\"})) >= $MinQuotaThreashold/100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per resource limits ($MinQuotaThreashold% and higher)",
   "type": "bargauge",
   "description": "Dynamic list of all resource based service quotas fetched by [aws-quota-checker](https://github.com/gravitational/aws-quota-checker)\n- https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html\n",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(max by(quota, exported_instance, service_code) ({__name__=~\"awsquota_.*[^_limit]$\", scope=\"INSTANCE\", region=~\"$region\"}) / max by(quota, exported_instance, service_code) ({__name__=~\"awsquota_.*_limit$\", scope=\"INSTANCE\", region=~\"$region\"}) >= $MinQuotaThreashold/100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}