on:
  pull_request:
    branches:
      - teleport
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: setup python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: "3.12"
      - name: install
        run: pip install .[dev]
      - name: build docker image
        run: docker build . --tag gravitational/aws-quota-checker:test
      - name: build helm chart
        working-directory: helm
        run: helm package .
